include = ["*.py", "**/pyproject.toml", "*.ipynb" ]
src = [ "." ]
target-version = "py311"

[lint]
ignore = [
  "E501",    # line too long
  "ISC001",  # Implicitly concatenated string literals on one line. Incompatible with "ruff format"
  "RET504",  # Unnecessary assignment to {name} before return statement
  "UP015",   # Unnecessary open mode parameters
]

select = [
  "ARG", # flake8-unused-arguments
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "E",   # pycodestyle
  "EM",  # flake8-errmsg
  "EXE", # flake8-executable
  "F",   # pyflakes
  "FA",  # flake8-future-annotations
  "FLY", # flynt
  "G",   # flake8-logging-format
  "I",   # isort
  "ICN", # flake8-import-conventions
  "INP", # flake8-no-pep420
  "ISC", # flake8-implicit-str-concat
  "N",   # pep8-naming
  "NPY", # NumPy-specific rules
  "PIE", # flake8-pie
  "PTH", # flake8-use-pathlib
  "Q",   # flake8-quotes
  "RET", # flake8-return
  "RSE", # flake8-raise
  "SIM", # flake8-simplify
  "SLF", # flake8-self
  "SLOT",# flake8-slots
  "TCH", # flake8-type-checking
  "T10", # flake8-debugger
  "UP",  # pyupgrade
  "W",   # pycodestyle, warnings
]
